#!/bin/sh /etc/rc.common
START=90

kcptun_pid=/var/run/kcptools_kcptun.pid
udp2raw_pid=/var/run/kcptools_udp2raw.pid

run_kcp()
{
	local server
	local serverport
	local client
	local clientport
	local password

	config_get server $1 server
	config_get serverport $1 serverport
	config_get client $1 client
	config_get clientport $1 clientport
	config_get password $1 password

	(kcptun-client -l $client:$clientport -r 127.0.0.1:22333 --key $password -mode fast2 -nocomp -sockbuf 16777217 -mtu 1300 >/dev/null 2>&1 ) & echo $!>$kcptun_pid &
	(udp2raw -c -l127.0.0.1:22333 -r$server:$serverport --raw-mode faketcp -a -k $password >/dev/null 2>&1 ) & echo $!>$udp2raw_pid &
}

start()
{
	config_load kcptools
	config_foreach run_kcp kcpconfig
}

stop()
{
	kill $(cat $udp2raw_pid)
	kill $(cat $kcptun_pid)
}
